-- ════════════════════════════════════════════════════════════════════════════
-- Custodia de faltantes · fase 3 (acta de faltantes y envío a custodia)
--
-- Correr con el usuario postgres ANTES de desplegar la versión con la fase 3:
-- hallazgo_inventario es de postgres y el usuario de la app no puede alterarla.
-- Es idempotente. Una sola transacción: si algo falla, no queda nada a medias.
-- Sirve en pgAdmin/DBeaver o en psql (en psql, con -v ON_ERROR_STOP=1).
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

-- 1. Acta de faltantes ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS acta_faltante (
    id_acta                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                   varchar(20),
    token                    varchar(40)  NOT NULL,
    id_persona               bigint       NOT NULL,
    persona_nombre           varchar(160) NOT NULL,
    persona_ci               varchar(20),
    persona_cargo            varchar(120),
    fecha_emision            timestamp(6) NOT NULL,
    usuario_emision          varchar(60),
    documento_respaldo       varchar(120),
    fecha_documento          date,
    observacion              text,
    total_bienes             integer      NOT NULL,
    contenido                text         NOT NULL,
    hash_contenido           varchar(64)  NOT NULL,
    estado_acta              varchar(15)  NOT NULL,
    motivo_anulacion         text,
    fecha_anulacion          timestamp(6),
    usuario_anulacion        varchar(60),
    _estado                  varchar(255),
    _fecha_registro          timestamp(6),
    _registro_id_usuario     bigint,
    _fecha_modificacion      timestamp(6),
    _modificacion_id_usuario bigint,
    CONSTRAINT uk_acta_falt_numero UNIQUE (numero),
    CONSTRAINT uk_acta_falt_token  UNIQUE (token),
    CONSTRAINT fk_acta_falt_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona)
);

CREATE INDEX IF NOT EXISTS idx_acta_falt_persona ON acta_faltante (id_persona);
CREATE INDEX IF NOT EXISTS idx_acta_falt_fecha   ON acta_faltante (fecha_emision);

-- Mismos permisos que ya tiene el usuario de la app sobre hallazgo_inventario
-- (así no hay que escribir su nombre acá, y sirve en cualquier copia de la base).
DO $$
DECLARE r record;
BEGIN
    FOR r IN SELECT DISTINCT grantee FROM information_schema.role_table_grants
              WHERE table_name = 'hallazgo_inventario' AND privilege_type = 'INSERT'
                AND grantee <> 'postgres'
    LOOP
        EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON acta_faltante TO %I', r.grantee);
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO %I',
                       pg_get_serial_sequence('acta_faltante', 'id_acta'), r.grantee);
    END LOOP;
END $$;

-- 2. El faltante sabe en qué acta se registró y cómo va su traslado ──────────

ALTER TABLE hallazgo_inventario ADD COLUMN IF NOT EXISTS id_acta       bigint;
ALTER TABLE hallazgo_inventario ADD COLUMN IF NOT EXISTS estado_envio  varchar(15);
ALTER TABLE hallazgo_inventario ADD COLUMN IF NOT EXISTS mensaje_envio text;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hall_acta') THEN
        ALTER TABLE hallazgo_inventario
            ADD CONSTRAINT fk_hall_acta FOREIGN KEY (id_acta) REFERENCES acta_faltante (id_acta);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_hall_acta         ON hallazgo_inventario (id_acta);
CREATE INDEX IF NOT EXISTS idx_hall_estado_envio ON hallazgo_inventario (estado_envio);

-- 3. Verificación ────────────────────────────────────────────────────────────
-- Tiene que dar: 3 | 1 | t
--   3 = columnas nuevas en hallazgo_inventario
--   1 = FK fk_hall_acta
--   t = el usuario de la app puede insertar en acta_faltante

SELECT (SELECT count(*) FROM information_schema.columns
         WHERE table_name = 'hallazgo_inventario'
           AND column_name IN ('id_acta', 'estado_envio', 'mensaje_envio'))         AS columnas,
       (SELECT count(*) FROM pg_constraint WHERE conname = 'fk_hall_acta')          AS fk,
       (SELECT bool_and(has_table_privilege(grantee, 'acta_faltante', 'INSERT'))
          FROM (SELECT DISTINCT grantee FROM information_schema.role_table_grants
                 WHERE table_name = 'hallazgo_inventario' AND privilege_type = 'INSERT'
                   AND grantee <> 'postgres') g)                                     AS app_puede;

COMMIT;
