-- ════════════════════════════════════════════════════════════════════════════
-- Auditoría de permisos de usuario (historial_permiso_usuario)
--
-- Qué se le agregó/quitó a cada usuario en sus permisos de menú, quién, cuándo, desde
-- qué IP y desde qué pantalla; y el respaldo que se restaura al volver a activarlo.
--
-- Correr con el usuario postgres ANTES de desplegar (o antes de reiniciar la app de
-- prueba): sin la tabla, guardar permisos y activar/desactivar usuarios fallan, porque
-- la auditoría va en la misma transacción que el cambio.
-- Es idempotente. Una sola transacción. pgAdmin/DBeaver, o psql con -v ON_ERROR_STOP=1.
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

CREATE TABLE IF NOT EXISTS historial_permiso_usuario (
    id_historial      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        bigint       NOT NULL,
    usuario           varchar(60),
    accion            varchar(30)  NOT NULL,
    origen            varchar(80),
    agregados         text,
    quitados          text,
    respaldo          text,
    cantidad_antes    integer,
    cantidad_despues  integer,
    detalle           text,
    id_actor          bigint,
    actor             varchar(60),
    rol_actor         varchar(40),
    ip                varchar(45),
    fecha             timestamp(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_hpu_usuario ON historial_permiso_usuario (id_usuario);
CREATE INDEX IF NOT EXISTS idx_hpu_fecha   ON historial_permiso_usuario (fecha);

-- Mismos permisos que ya tiene el usuario de la app sobre usuario_opcion.
DO $$
DECLARE r record;
BEGIN
    FOR r IN SELECT DISTINCT grantee FROM information_schema.role_table_grants
              WHERE table_name = 'usuario_opcion' AND privilege_type = 'INSERT'
                AND grantee <> 'postgres'
    LOOP
        EXECUTE format('GRANT SELECT, INSERT ON historial_permiso_usuario TO %I', r.grantee);
        EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO %I',
                       pg_get_serial_sequence('historial_permiso_usuario', 'id_historial'), r.grantee);
    END LOOP;
END $$;

-- Solo SELECT e INSERT a propósito: la app agrega historial, nunca lo corrige ni lo borra.
--
-- Verificación: tiene que dar  t | t
-- Si la segunda columna da f (el usuario de la app es dueño de usuario_opcion y por eso no
-- figura como "grantee"), otorgar a mano con su nombre:
--   GRANT SELECT, INSERT ON historial_permiso_usuario TO <usuario_app>;
--   GRANT USAGE, SELECT ON SEQUENCE historial_permiso_usuario_id_historial_seq TO <usuario_app>;
SELECT to_regclass('historial_permiso_usuario') IS NOT NULL AS tabla_creada,
       EXISTS (SELECT 1 FROM information_schema.role_table_grants
                WHERE table_name = 'historial_permiso_usuario' AND grantee <> 'postgres') AS permisos_otorgados;

COMMIT;
