spring.application.name=SistemasActivosFijosUAP
server.port=9696
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_activos_fijos
spring.datasource.username=admin
spring.datasource.password=usic_2025
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update

#openai
spring.ai.openai.api-key=TU_CLAVE_API_DE_OPENAI