spring.application.name=SistemasActivosFijosUAP
server.port=9696
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_activos_fijos
spring.datasource.username=postgres
spring.datasource.password=Srkiwi2.0
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update

#openai
spring.ai.openai.api-key=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

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
